name: Test-Build

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Install Node.js on the runner
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      # Install Newman and the HTML Extra Reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Create Directory for Test Results
      - name: Make Directory for results
        run: mkdir -p allure-report

      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          newman run petstore.collection.json \
          -r htmlextra \
          --reporter-htmlextra-export allure-report/htmlreport.html \
          --reporter-htmlextra-darkTheme

      # Deploy Report to GitHub Pages
      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: report

      # Push Report to Other Branch
      - name: Push Report to Other Branch
        if: always()
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b report
          git add -f report
          git commit -m "Add report"
          git push origin report --force
      
      # Update GitHub Pages link in README
      - name: Update GitHub Pages link in README
        run: |
          REPORT_LINK="https://${{ github.oleg-lukanov }}.github.io/${{ github.Postman-newman-ghActions }}"
          sed -i "s|Allure Report|Allure Report: [View Report](${REPORT_LINK})|" README.md
          git add README.md
          git commit -m "Update Allure Report link in README"
          git push origin main
